reconnix_main:
    resource: "@ReconnixCmsBundle/Resources/config/routing.yml"
    prefix:   /

reconnix_main_admin:
    resource: "@ReconnixCmsBundle/Resources/config/routing.admin.yml"
    prefix:	  /admin