parameters:
#    reconnix_content_wizard.example.class: Reconnix\ContentWizardBundle\Example

services:
#    reconnix_content_wizard.example:
#        class: %reconnix_content_wizard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
