reconnix_main_admin_posts_index:
    pattern:  /
    defaults: { _controller: ReconnixCmsBundle:Admin/Posts:index }

reconnix_main_admin_posts_add:
    pattern:  /add
    defaults: { _controller: ReconnixCmsBundle:Admin/Posts:add }

reconnix_main_admin_posts_edit:
    pattern:  /edit/{id}
    defaults: { _controller: ReconnixCmsBundle:Admin/Posts:edit }

reconnix_main_admin_posts_delete:
    pattern:  /delete/{id}
    defaults: { _controller: ReconnixCmsBundle:Admin/Posts:delete }
