reconnix_main_admin_pages_index:
    pattern:  /
    defaults: { _controller: ReconnixMainBundle:Admin/Pages:index }

reconnix_main_admin_pages_add:
    pattern:  /add
    defaults: { _controller: ReconnixMainBundle:Admin/Pages:add }

reconnix_main_admin_pages_edit:
    pattern:  /edit/{id}
    defaults: { _controller: ReconnixMainBundle:Admin/Pages:edit }