reconnix_main_admin_index:
    pattern:  /
    defaults: { _controller: ReconnixMainBundle:Admin/Admin:index }

reconnix_main_admin_pages:
    resource: "@ReconnixMainBundle/Resources/config/routing.admin.pages.yml"
    prefix: /pages

reconnix_main_admin_blocks:
    resource: "@ReconnixMainBundle/Resources/config/routing.admin.blocks.yml"
    prefix: /blocks

reconnix_main_admin_posts:
    resource: "@ReconnixMainBundle/Resources/config/routing.admin.posts.yml"
    prefix: /posts

reconnix_main_admin_content_wizard:
    resource: "@ReconnixMainBundle/Resources/config/routing.admin.content_wizard.yml"
    prefix: /content-wizard

reconnix_main_admin_templates:
    resource: "@ReconnixMainBundle/Resources/config/routing.admin.templates.yml"
    prefix: /templates