reconnix_main_admin_menu_index:
    pattern:  /
    defaults: { _controller: ReconnixMainBundle:Admin/Menu:index}

reconnix_main_admin_menu_add:
    pattern:  /add
    defaults: { _controller: ReconnixMainBundle:Admin/Menu:add}

reconnix_main_admin_menu_edit:
    pattern:  /edit/{id}
    defaults: { _controller: ReconnixMainBundle:Admin/Menu:edit}

reconnix_main_admin_menu_delete:
    pattern:  /delete/{id}
    defaults: { _controller: ReconnixMainBundle:Admin/Menu:delete }