parameters:
#    reconnix_main.example.class: Reconnix\MainBundle\Example

services:
#    reconnix_main.example:
#        class: %reconnix_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    reconnix_main_admin.pages:
        class: 			Reconnix\MainBundle\Controller\Admin\PagesController
        arguments:		['@doctrine', '@form.factory', '@templating', '@request_stack', '@router']

    content_base:
        class: Reconnix\MainBundle\Classes\ContentCreator
        arguments:		['@form.factory']

    page_renderer:
        class:  Reconnix\MainBundle\Classes\PageRenderer\PageRenderer
        arguments: ['@doctrine', '@twig']