Reconnix\MainBundle\Entity\Block:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 32
        content:
            - NotBlank: ~