parameters:
#    reconnix_dep_inj.example.class: Reconnix\DepInjBundle\Example
    address.name: one

services:
#    reconnix_dep_inj.example:
#        class: %reconnix_dep_inj.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    address:
        class: Reconnix\DepInjBundle\Classes\Address
        arguments: ['%address.name%']
    user:
        class: Reconnix\DepInjBundle\Classes\User
        arguments: ['@doctrine']
        calls:
            - [setAddress, ["@address"]]